server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: spring-jms
  rabbitmq:
    port: 5672
    username: cloud
    password: cloud
    host: 127.0.0.1
    publisher-confirms: true
    virtual-host: /cloud
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        acknowledge-mode: manual
        prefetch: 1
  kafka:
    bootstrap-servers: node-2:9092,node-3:9092,node-4:9092
    producer:
      retries:
      batch-size: 16384
      buffer-memory: 33554432
      compressionType: snappy
      acks: all
    consumer:
      group-id: 0
      auto-offset-reset: earliest
      enable-auto-commit: true

info:
   app:
      name: spring-boot-actuator
      version: 1.0.0
