profiles:
  active: provicer

---
spring:
  profiles: provider
  dubbo:
    server: true
    application:
      name: provider
    registry:
      address: zookeeper://39.108.125.41:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.andy.dubbo.provider
server:
  port: 8080

---
spring:
  profiles: consumer
  application:
    name: spring-dubbo
  dubbo:
    application:
      name: provider
    registry:
      address: zookeeper://39.108.125.41:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.andy.dubbo.provider

server:
  port: 8080

