spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiro?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .jsp
mybatis:
  mapper-locations: mybatis/mappers/*.xml
  type-aliases-package: com.andy.shiro.entity.rbac
