server:
  servlet:
    path: /
  port: 8080
spring:
  application:
    name: spring-amqp
  rabbitmq:
    port: 5672
    username: cloud
    password: cloud
    host: 127.0.0.1
    publisher-confirms: true
    virtual-host: /cloud


#management:
#  security:
#    enabled: false #关掉安全认证
#  port: 8088 #管理端口调整成8088
#  context-path: /monitor #actuator的访问路径
#endpoints:
#  shutdown:
#    enabled: true
info:
   app:
      name: spring-boot-actuator
      version: 1.0.0

