server:
  servlet:
    path: /
  port: 8080

spring:
  application:
    name: spring-seurity
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

