spring:
  cache:
    type: redis
  redis:
    port: 6379
    host: 127.0.0.1
    database: 5
#    password: admin
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        min-idle: 0
        max-idle: 8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.125.41:3306/boot?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    show-sql: true
    open-in-view: false


mybatis:
  configuration:
    # 全局映射器启用缓存
    cache-enabled: true
    # 按需加载字段(加载字段由SQL指定),不会加载关联表的所有字段,以提高性能
    aggressive-lazy-loading: false
    # 查询时,关闭关联对象及时加载以提高性能
    lazy-loading-enabled: false
    #对于批量更新操作缓存SQL以提高性能
    default-executor-type: reuse
    #允许返回不同的结果集以达到通用的效果
    multiple-result-sets-enabled: true
    #数据库执行超时时间
    default-statement-timeout: 25000
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.andy.entity
